### ISSUE TITLE
Continue to update?

### ISSUE THREAD

**Issue by LiZeC123** [AaronLiuIsCool/Effective-Java-Third-Edition-Reading-Notes#6]
I am reading `<<Effective Java>>` now. So I am very happy to find the reading notes about this book, but you had stopped the update for about one week.  will this project be updated continually?

**Comment by AaronLiuIsCool** [comment]
Thanks for the comments. I got an accident last week and stopped reading for a few days. However, I will keep reading this week and continue to take notes of it. Feel free to share your thoughts on each note. 

Cheers,

Aaron.
